### ISSUE TITLE
Crash on specific Message

### ISSUE THREAD

**Issue by Mike-131** [fourtf/chatterino#116]
If you are receiving a message from a chat the application will crash. Rejoining the channel when the message is still sent in the "older messages" will result in chatterino crashing again. It looks like some kind of rendering issue.

This is reproduceable when sending the following message to a channel:
"﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽" (without "")

**Comment by gempir** [comment]
`﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽`

for better copy paste

**Comment by gempir** [comment]
Seems to be an issue with SharpDX

```
SharpDX.SharpDXException occurred
  HResult=0x8007007A
  Message=HRESULT: [0x8007007A], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: The data area passed to a system call is too small.

  Source=SharpDX
  StackTrace:
   at SharpDX.Result.CheckError()
   at SharpDX.DirectWrite.TextLayout.GetMetrics(TextMetrics& textMetrics)
   at Chatterino.WinformsGuiEngine.<>c__DisplayClass19_0.<MeasureStringSize>b__1(String s)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Chatterino.Common.Message.CalculateBounds(Object graphics, Int32 width, Boolean enableHatEmotes)
   at Chatterino.Controls.MessageContainerControl.updateMessageBounds(Boolean emoteChanged)
   at Chatterino.Controls.ChatControl.updateMessageBounds(Boolean emoteChanged)
   at Chatterino.Controls.ChatControl.Channel_MessageAdded(Object sender, MessageAddedEventArgs e)
   at Chatterino.Common.TwitchChannel.AddMessage(Message message)
   at Chatterino.Common.IrcManager.<>c__DisplayClass46_0.<ReadConnection_MessageReceived>b__0(TwitchChannel c)
   at Chatterino.Common.Util.Process[T](T element, Action`1 action)
   at Chatterino.Common.IrcManager.ReadConnection_MessageReceived(Object sender, MessageEventArgs e)
   at TwitchIrc.IrcConnection.<>c__DisplayClass27_0.<connect>b__1()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by gempir** [comment]
bca4ff9f6513392d8d58cb923685d0dc7257e945
